# Generated by Django 4.2.6 on 2023-10-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="address_detail",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mail_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(default="consumer", max_length=100),
        ),
    ]
