# Generated by Django 4.2.6 on 2023-10-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("seller", "Seller"), ("buyer", "Buyer"), ("admin", "Admin")],
                max_length=100,
            ),
        ),
    ]
