# Generated by Django 4.2.6 on 2023-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("notice_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("regdate", models.DateField(auto_now_add=True)),
                ("notice_type", models.IntegerField()),
                ("user_type", models.CharField(max_length=25)),
            ],
        ),
    ]
