# Generated by Django 4.2.6 on 2023-11-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Qna",
            fields=[
                ("qna_id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=25)),
                ("subject", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("regdate", models.DateField(auto_now_add=True)),
                ("status", models.IntegerField(default=0)),
                ("user_type", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("regdate", models.DateTimeField(auto_now_add=True)),
                (
                    "qna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qna.qna"
                    ),
                ),
            ],
        ),
    ]
