# Generated by Django 4.2.6 on 2023-11-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_remove_qna_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='nickname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='qna',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
