# Generated by Django 4.2.6 on 2023-11-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_qna_nickname_alter_qna_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='regdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
