# Generated by Django 4.2.6 on 2023-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_alter_qna_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
