# Generated by Django 4.2.6 on 2023-11-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='nickname',
            field=models.CharField(max_length=25),
        ),
    ]
