# Generated by Django 4.2.6 on 2023-11-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
