# Generated by Django 4.2.6 on 2023-11-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE order_order AUTO_INCREMENT = 20231127;"),
    ]
