# Generated by Django 4.2.6 on 2023-11-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon', models.IntegerField()),
                ('point', models.IntegerField()),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField()),
            ],
        ),
    ]
