# Generated by Django 4.2.6 on 2023-11-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='regdate',
            field=models.DateTimeField(),
        ),
    ]
