# Generated by Django 4.2.6 on 2023-11-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_coupon_alter_event_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
