# Generated by Django 4.2.6 on 2023-11-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coupon',
            field=models.IntegerField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='point',
            field=models.IntegerField(default='-', null=True),
        ),
    ]
