# Generated by Django 4.2.6 on 2023-11-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_coupon_alter_event_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coupon',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='point',
            field=models.IntegerField(null=True),
        ),
    ]
