# Generated by Django 4.2.6 on 2023-11-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_coupon_alter_event_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='event',
            name='point',
        ),
    ]
