# Generated by Django 4.2.6 on 2023-11-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm_products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eco", models.CharField(max_length=100)),
                ("kind", models.CharField(max_length=100)),
                ("crop", models.IntegerField(default=0)),
                ("center", models.CharField(max_length=100)),
                ("state", models.CharField(default="등록대기", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm_id",
                    models.ForeignKey(
                        db_column="farm_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farms.farms",
                    ),
                ),
            ],
        ),
    ]
