# Generated by Django 4.2.6 on 2023-11-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm_products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_id", models.IntegerField()),
                ("eco", models.CharField(max_length=100)),
                ("kind", models.CharField(max_length=100)),
                ("crop", models.IntegerField(default=0)),
                ("unit_type", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
