# Generated by Django 4.2.6 on 2023-11-07 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0005_farms_latitude_farms_longitude"),
        ("farm_product", "0003_farm_products_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm_products",
            name="center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farms.farms"
            ),
        ),
    ]
