# Generated by Django 4.2.6 on 2023-11-07 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0005_farms_latitude_farms_longitude"),
        ("farm_product", "0004_alter_farm_products_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm_products",
            name="center",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="farm_products",
            name="farm_id",
            field=models.ForeignKey(
                db_column="farm_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="farms.farms",
            ),
        ),
    ]
