# Generated by Django 4.2.6 on 2023-11-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm_product", "0005_alter_farm_products_center_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm_products",
            name="center",
        ),
    ]
