# Generated by Django 4.2.6 on 2023-11-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm_product", "0006_remove_farm_products_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm_products",
            name="center",
            field=models.CharField(default="고창", max_length=100),
            preserve_default=False,
        ),
    ]
