# Generated by Django 4.2.6 on 2023-11-07 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm_product", "0007_farm_products_center"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm_products",
            name="unit_type",
        ),
    ]
