# Generated by Django 4.2.6 on 2023-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0004_farms_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farms",
            name="mail_number",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
