# Generated by Django 4.2.6 on 2023-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0005_alter_farms_mail_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="farms",
            name="center",
            field=models.CharField(default="광주", max_length=100),
            preserve_default=False,
        ),
    ]
